name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend'
      - '!backend/.editorconfig'
      - '!backend/.gitignore'
      - '!backend/*.md'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend'
      - '!backend/.editorconfig'
      - '!backend/.gitignore'
      - '!backend/*.md'
  workflow_dispatch:
jobs:
  build:
    runs-on: maven:3-eclipse-temurin-17
    env:
      working-directory: backend
    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ${{env.working-directory}}
      run: mvn -B install site
